'''
You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.

Write a function that returns the letter that was added to str_2.

Examples:

csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"
Notes:

str_1 and str_2 both consist of only lowercase alpha characters.
[execution time limit] 4 seconds (py3)

[input] string str_1

[input] string str_2

[output] string

- Input:
str_1: "bcde"
str_2: "bcdef"
Expected Output:
"f"

- Input:
str_1: ""
str_2: "z"
Expected Output:
"z"

Input:
str_1: "xqmxtheyvpdqounqmfyaqdqxwe"
str_2: "xqmxtheyvpdqounqmfyaqxdqxwe"
Expected Output:
"x"
'''

def csFindAddedLetter(str_1, str_2):
    # Sorted two strings into alphabetic 
    str_1 = sorted(str_1)
    str_2 = sorted(str_2)
    #  Loop through str_1 to check if each word is as same as str_2 or not 
    for i in range(len(str_1)):
        if str_1[i] != str_2[i]:
        # If not then return the index of that word in str_2
            return str_2[i]
    # give me the last letter of the string two
    return str_2[-1]

print(csFindAddedLetter("bcde", "bcdef"))
print(csFindAddedLetter("","z" ))
print(csFindAddedLetter("xqmxtheyvpdqounqmfyaqdqxwe","xqmxtheyvpdqounqmfyaqxdqxwe"))
